version: '3'

services:
  # CORS Proxy Server ด้วย Bun
  cors-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35757:35757"
    volumes:
      - ./proxy-server.js:/app/proxy-server.js
    restart: always
    container_name: manga-finder-cors-proxy
    networks:
      - manga-network
  
  # เว็บเซิร์ฟเวอร์สำหรับแสดงผลหน้าเว็บ
  web-server:
    image: oven/bun:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "35756:35756"
    command: bun run --hot -p 35756 --smol index.html
    container_name: manga-finder-web
    restart: always
    depends_on:
      - cors-proxy
    networks:
      - manga-network

networks:
  manga-network:
    driver: bridge
