services:
  # เว็บเซิร์ฟเวอร์สำหรับแสดงผลหน้าเว็บ
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "35756:35756"
    container_name: manga-finder-web
    restart: unless-stopped
